<%@ Page Title="" Language="C#" MasterPageFile="~/View/Main.Master" AutoEventWireup="true" CodeBehind="Cart.aspx.cs" Inherits="Mukicik_backend.View.Cart" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:PlaceHolder runat="server" ID="placeholder_usercart" Visible="false">
    <table>
        <tr>
            <td>userCart</td>
            <td></td>
        </tr>
        <tr>
            <td><asp:GridView ID="gvTransaction" AutoGenerateDeleteButton="true" OnRowDeleting="gvTransactionDetail_RowDeleting" runat="server"></asp:GridView></td>
            <td></td>
        </tr>
    </table>
    <table>
        <tr>
            <td>Total : </td>
            <td><asp:TextBox ID="input_totalPrice" ReadOnly="true" Text="" runat="server" /></td>
        </tr>
        <tr>
            <td><asp:Button ID="button_buy" Text="Buy" runat="server" OnClick="button_buy_Click"/></td>
            <td><asp:Button ID="button_cancel" Text="Cancel" runat="server" OnClick="button_cancel_Click"/></td>
            <td> <asp:Label Text="" ID="onrowdeletinglabel" runat="server" /></td>
        </tr>
    </table>
    </asp:PlaceHolder>
</asp:Content>
