//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mukicik_backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int productID { get; set; }
        public string productName { get; set; }
        public int productPrice { get; set; }
        public string productImage { get; set; }
        public double productRating { get; set; }
        public int productStock { get; set; }
        public int categoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
