//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mukicik_backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int detailTransactionID { get; set; }
        public int Quantity { get; set; }
        public int transactionID { get; set; }
        public int productID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
