//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mukicik_backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int userID { get; set; }
        public string userName { get; set; }
        public string userEmail { get; set; }
        public string userPassword { get; set; }
        public string userGender { get; set; }
        public string userDOB { get; set; }
        public string userRole { get; set; }
        public string userProfilePicture { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
